id: api-netlify

info:
  name: Netlify API Test
  author: dwisiswant0
  reference: https://docs.netlify.com/api/get-started/
  severity: info
  tags: token-spray,netlify

self-contained: true
requests:
  - method: GET
    path:
      - "https://api.netlify.com/api/v1/sites"
    headers:
      Authorization: Bearer {{token}}

    matchers:
      - type: status
        status:
          - 200
